/* generated by tools/wii/engine_unsupported.py - do not edit

Xbox SDK entry points the Wii engine build does not implement (HWI-015).
Each has the SDK's prototype, reports itself as unsupported and fails
(see the script). */

#include "platform.h"
#include "wii_platform.h"

/* ---------- d3d8 */

void __stdcall D3DCubeTexture_LockRect(struct D3DCubeTexture * a0, enum _D3DCUBEMAP_FACES a1, unsigned int a2, struct _D3DLOCKED_RECT * a3, const struct tagRECT * a4, unsigned long a5)
{
	wii_unsupported("d3d8", "D3DCubeTexture_LockRect");
}

void __stdcall D3DDevice_Begin(enum _D3DPRIMITIVETYPE a0)
{
	wii_unsupported("d3d8", "D3DDevice_Begin");
}

void __stdcall D3DDevice_BeginVisibilityTest(void)
{
	wii_unsupported("d3d8", "D3DDevice_BeginVisibilityTest");
}

void __stdcall D3DDevice_BlockUntilVerticalBlank(void)
{
	wii_unsupported("d3d8", "D3DDevice_BlockUntilVerticalBlank");
}

void __stdcall D3DDevice_Clear(unsigned long a0, const struct _D3DRECT * a1, unsigned long a2, unsigned long a3, float a4, unsigned long a5)
{
	wii_unsupported("d3d8", "D3DDevice_Clear");
}

long __stdcall D3DDevice_CreateCubeTexture(unsigned int a0, unsigned int a1, unsigned long a2, enum _D3DFORMAT a3, unsigned long a4, struct D3DCubeTexture ** a5)
{
	wii_unsupported("d3d8", "D3DDevice_CreateCubeTexture");
	return E_FAIL;
}

long __stdcall D3DDevice_CreateIndexBuffer(unsigned int a0, unsigned long a1, enum _D3DFORMAT a2, unsigned long a3, struct D3DIndexBuffer ** a4)
{
	wii_unsupported("d3d8", "D3DDevice_CreateIndexBuffer");
	return E_FAIL;
}

long __stdcall D3DDevice_CreatePalette(enum _D3DPALETTESIZE a0, struct D3DPalette ** a1)
{
	wii_unsupported("d3d8", "D3DDevice_CreatePalette");
	return E_FAIL;
}

long __stdcall D3DDevice_CreateTexture(unsigned int a0, unsigned int a1, unsigned int a2, unsigned long a3, enum _D3DFORMAT a4, unsigned long a5, struct D3DTexture ** a6)
{
	wii_unsupported("d3d8", "D3DDevice_CreateTexture");
	return E_FAIL;
}

long __stdcall D3DDevice_CreateVertexBuffer(unsigned int a0, unsigned long a1, unsigned long a2, unsigned long a3, struct D3DVertexBuffer ** a4)
{
	wii_unsupported("d3d8", "D3DDevice_CreateVertexBuffer");
	return E_FAIL;
}

long __stdcall D3DDevice_CreateVertexShader(const unsigned long * a0, const unsigned long * a1, unsigned long * a2, unsigned long a3)
{
	wii_unsupported("d3d8", "D3DDevice_CreateVertexShader");
	return E_FAIL;
}

long __stdcall D3DDevice_CreateVolumeTexture(unsigned int a0, unsigned int a1, unsigned int a2, unsigned int a3, unsigned long a4, enum _D3DFORMAT a5, unsigned long a6, struct D3DVolumeTexture ** a7)
{
	wii_unsupported("d3d8", "D3DDevice_CreateVolumeTexture");
	return E_FAIL;
}

void __stdcall D3DDevice_DeleteVertexShader(unsigned long a0)
{
	wii_unsupported("d3d8", "D3DDevice_DeleteVertexShader");
}

void __stdcall D3DDevice_DrawIndexedVertices(enum _D3DPRIMITIVETYPE a0, unsigned int a1, const unsigned short * a2)
{
	wii_unsupported("d3d8", "D3DDevice_DrawIndexedVertices");
}

void __stdcall D3DDevice_DrawVertices(enum _D3DPRIMITIVETYPE a0, unsigned int a1, unsigned int a2)
{
	wii_unsupported("d3d8", "D3DDevice_DrawVertices");
}

void __stdcall D3DDevice_End(void)
{
	wii_unsupported("d3d8", "D3DDevice_End");
}

long __stdcall D3DDevice_EndVisibilityTest(unsigned long a0)
{
	wii_unsupported("d3d8", "D3DDevice_EndVisibilityTest");
	return E_FAIL;
}

void __stdcall D3DDevice_GetBackBuffer(int a0, unsigned long a1, struct D3DSurface ** a2)
{
	wii_unsupported("d3d8", "D3DDevice_GetBackBuffer");
}

long __stdcall D3DDevice_GetDepthStencilSurface(struct D3DSurface ** a0)
{
	wii_unsupported("d3d8", "D3DDevice_GetDepthStencilSurface");
	return E_FAIL;
}

void __stdcall D3DDevice_GetDeviceCaps(struct _D3DCAPS8 * a0)
{
	wii_unsupported("d3d8", "D3DDevice_GetDeviceCaps");
}

void __stdcall D3DDevice_GetTransform(enum _D3DTRANSFORMSTATETYPE a0, struct _D3DMATRIX * a1)
{
	wii_unsupported("d3d8", "D3DDevice_GetTransform");
}

void __stdcall D3DDevice_GetVertexShaderSize(unsigned long a0, unsigned int * a1)
{
	wii_unsupported("d3d8", "D3DDevice_GetVertexShaderSize");
}

long __stdcall D3DDevice_GetVisibilityTestResult(unsigned long a0, unsigned int * a1, unsigned __int64 * a2)
{
	wii_unsupported("d3d8", "D3DDevice_GetVisibilityTestResult");
	return E_FAIL;
}

void __stdcall D3DDevice_InsertCallback(enum _D3DCALLBACKTYPE a0, void (*a1)(unsigned long), unsigned long a2)
{
	wii_unsupported("d3d8", "D3DDevice_InsertCallback");
}

int __stdcall D3DDevice_IsBusy(void)
{
	wii_unsupported("d3d8", "D3DDevice_IsBusy");
	return FALSE;
}

void __stdcall D3DDevice_KickPushBuffer(void)
{
	wii_unsupported("d3d8", "D3DDevice_KickPushBuffer");
}

void __stdcall D3DDevice_LoadVertexShader(unsigned long a0, unsigned long a1)
{
	wii_unsupported("d3d8", "D3DDevice_LoadVertexShader");
}

long __stdcall D3DDevice_PersistDisplay(void)
{
	wii_unsupported("d3d8", "D3DDevice_PersistDisplay");
	return E_FAIL;
}

void __stdcall D3DDevice_Present(const struct tagRECT * a0, const struct tagRECT * a1, void * a2, void * a3)
{
	wii_unsupported("d3d8", "D3DDevice_Present");
}

unsigned long __stdcall D3DDevice_Release(void)
{
	wii_unsupported("d3d8", "D3DDevice_Release");
	return 0;
}

void __stdcall D3DDevice_SelectVertexShader(unsigned long a0, unsigned long a1)
{
	wii_unsupported("d3d8", "D3DDevice_SelectVertexShader");
}

void __stdcall D3DDevice_SetFlickerFilter(unsigned long a0)
{
	wii_unsupported("d3d8", "D3DDevice_SetFlickerFilter");
}

void __stdcall D3DDevice_SetIndices(struct D3DIndexBuffer * a0, unsigned int a1)
{
	wii_unsupported("d3d8", "D3DDevice_SetIndices");
}

void __stdcall D3DDevice_SetPalette(unsigned long a0, struct D3DPalette * a1)
{
	wii_unsupported("d3d8", "D3DDevice_SetPalette");
}

void __stdcall D3DDevice_SetPixelShaderProgram(struct _D3DPixelShaderDef * a0)
{
	wii_unsupported("d3d8", "D3DDevice_SetPixelShaderProgram");
}

void __stdcall D3DDevice_SetRenderStateNotInline(enum _D3DRENDERSTATETYPE a0, unsigned long a1)
{
	wii_unsupported("d3d8", "D3DDevice_SetRenderStateNotInline");
}

void __stdcall D3DDevice_SetRenderState_BackFillMode(unsigned long a0)
{
	wii_unsupported("d3d8", "D3DDevice_SetRenderState_BackFillMode");
}

void __stdcall D3DDevice_SetRenderState_CullMode(unsigned long a0)
{
	wii_unsupported("d3d8", "D3DDevice_SetRenderState_CullMode");
}

void __fastcall D3DDevice_SetRenderState_Deferred(enum _D3DRENDERSTATETYPE a0, unsigned long a1)
{
	wii_unsupported("d3d8", "D3DDevice_SetRenderState_Deferred");
}

void __stdcall D3DDevice_SetRenderState_DoNotCullUncompressed(unsigned long a0)
{
	wii_unsupported("d3d8", "D3DDevice_SetRenderState_DoNotCullUncompressed");
}

void __stdcall D3DDevice_SetRenderState_Dxt1NoiseEnable(unsigned long a0)
{
	wii_unsupported("d3d8", "D3DDevice_SetRenderState_Dxt1NoiseEnable");
}

void __stdcall D3DDevice_SetRenderState_EdgeAntiAlias(unsigned long a0)
{
	wii_unsupported("d3d8", "D3DDevice_SetRenderState_EdgeAntiAlias");
}

void __stdcall D3DDevice_SetRenderState_FillMode(unsigned long a0)
{
	wii_unsupported("d3d8", "D3DDevice_SetRenderState_FillMode");
}

void __stdcall D3DDevice_SetRenderState_FogColor(unsigned long a0)
{
	wii_unsupported("d3d8", "D3DDevice_SetRenderState_FogColor");
}

void __stdcall D3DDevice_SetRenderState_FrontFace(unsigned long a0)
{
	wii_unsupported("d3d8", "D3DDevice_SetRenderState_FrontFace");
}

void __stdcall D3DDevice_SetRenderState_LineWidth(unsigned long a0)
{
	wii_unsupported("d3d8", "D3DDevice_SetRenderState_LineWidth");
}

void __stdcall D3DDevice_SetRenderState_LogicOp(unsigned long a0)
{
	wii_unsupported("d3d8", "D3DDevice_SetRenderState_LogicOp");
}

void __stdcall D3DDevice_SetRenderState_MultiSampleAntiAlias(unsigned long a0)
{
	wii_unsupported("d3d8", "D3DDevice_SetRenderState_MultiSampleAntiAlias");
}

void __stdcall D3DDevice_SetRenderState_MultiSampleMask(unsigned long a0)
{
	wii_unsupported("d3d8", "D3DDevice_SetRenderState_MultiSampleMask");
}

void __stdcall D3DDevice_SetRenderState_MultiSampleType(unsigned long a0)
{
	wii_unsupported("d3d8", "D3DDevice_SetRenderState_MultiSampleType");
}

void __stdcall D3DDevice_SetRenderState_NormalizeNormals(unsigned long a0)
{
	wii_unsupported("d3d8", "D3DDevice_SetRenderState_NormalizeNormals");
}

void __stdcall D3DDevice_SetRenderState_OcclusionCullEnable(unsigned long a0)
{
	wii_unsupported("d3d8", "D3DDevice_SetRenderState_OcclusionCullEnable");
}

void __stdcall D3DDevice_SetRenderState_PSTextureModes(unsigned long a0)
{
	wii_unsupported("d3d8", "D3DDevice_SetRenderState_PSTextureModes");
}

void __stdcall D3DDevice_SetRenderState_RopZCmpAlwaysRead(unsigned long a0)
{
	wii_unsupported("d3d8", "D3DDevice_SetRenderState_RopZCmpAlwaysRead");
}

void __stdcall D3DDevice_SetRenderState_RopZRead(unsigned long a0)
{
	wii_unsupported("d3d8", "D3DDevice_SetRenderState_RopZRead");
}

void __stdcall D3DDevice_SetRenderState_ShadowFunc(unsigned long a0)
{
	wii_unsupported("d3d8", "D3DDevice_SetRenderState_ShadowFunc");
}

void __fastcall D3DDevice_SetRenderState_Simple(unsigned long a0, unsigned long a1)
{
	wii_unsupported("d3d8", "D3DDevice_SetRenderState_Simple");
}

void __stdcall D3DDevice_SetRenderState_StencilCullEnable(unsigned long a0)
{
	wii_unsupported("d3d8", "D3DDevice_SetRenderState_StencilCullEnable");
}

void __stdcall D3DDevice_SetRenderState_StencilEnable(unsigned long a0)
{
	wii_unsupported("d3d8", "D3DDevice_SetRenderState_StencilEnable");
}

void __stdcall D3DDevice_SetRenderState_StencilFail(unsigned long a0)
{
	wii_unsupported("d3d8", "D3DDevice_SetRenderState_StencilFail");
}

void __stdcall D3DDevice_SetRenderState_TextureFactor(unsigned long a0)
{
	wii_unsupported("d3d8", "D3DDevice_SetRenderState_TextureFactor");
}

void __stdcall D3DDevice_SetRenderState_TwoSidedLighting(unsigned long a0)
{
	wii_unsupported("d3d8", "D3DDevice_SetRenderState_TwoSidedLighting");
}

void __stdcall D3DDevice_SetRenderState_VertexBlend(unsigned long a0)
{
	wii_unsupported("d3d8", "D3DDevice_SetRenderState_VertexBlend");
}

void __stdcall D3DDevice_SetRenderState_YuvEnable(unsigned long a0)
{
	wii_unsupported("d3d8", "D3DDevice_SetRenderState_YuvEnable");
}

void __stdcall D3DDevice_SetRenderState_ZBias(unsigned long a0)
{
	wii_unsupported("d3d8", "D3DDevice_SetRenderState_ZBias");
}

void __stdcall D3DDevice_SetRenderState_ZEnable(unsigned long a0)
{
	wii_unsupported("d3d8", "D3DDevice_SetRenderState_ZEnable");
}

void __stdcall D3DDevice_SetRenderTarget(struct D3DSurface * a0, struct D3DSurface * a1)
{
	wii_unsupported("d3d8", "D3DDevice_SetRenderTarget");
}

void __stdcall D3DDevice_SetShaderConstantMode(unsigned long a0)
{
	wii_unsupported("d3d8", "D3DDevice_SetShaderConstantMode");
}

void __stdcall D3DDevice_SetSoftDisplayFilter(int a0)
{
	wii_unsupported("d3d8", "D3DDevice_SetSoftDisplayFilter");
}

void __stdcall D3DDevice_SetStreamSource(unsigned int a0, struct D3DVertexBuffer * a1, unsigned int a2)
{
	wii_unsupported("d3d8", "D3DDevice_SetStreamSource");
}

void __stdcall D3DDevice_SetTexture(unsigned long a0, struct D3DBaseTexture * a1)
{
	wii_unsupported("d3d8", "D3DDevice_SetTexture");
}

void __stdcall D3DDevice_SetTextureState_BorderColor(unsigned long a0, unsigned long a1)
{
	wii_unsupported("d3d8", "D3DDevice_SetTextureState_BorderColor");
}

void __stdcall D3DDevice_SetTextureState_BumpEnv(unsigned long a0, enum _D3DTEXTURESTAGESTATETYPE a1, unsigned long a2)
{
	wii_unsupported("d3d8", "D3DDevice_SetTextureState_BumpEnv");
}

void __stdcall D3DDevice_SetTextureState_ColorKeyColor(unsigned long a0, unsigned long a1)
{
	wii_unsupported("d3d8", "D3DDevice_SetTextureState_ColorKeyColor");
}

void __fastcall D3DDevice_SetTextureState_Deferred(unsigned long a0, enum _D3DTEXTURESTAGESTATETYPE a1, unsigned long a2)
{
	wii_unsupported("d3d8", "D3DDevice_SetTextureState_Deferred");
}

void __stdcall D3DDevice_SetTextureState_TexCoordIndex(unsigned long a0, unsigned long a1)
{
	wii_unsupported("d3d8", "D3DDevice_SetTextureState_TexCoordIndex");
}

void __stdcall D3DDevice_SetTransform(enum _D3DTRANSFORMSTATETYPE a0, const struct _D3DMATRIX * a1)
{
	wii_unsupported("d3d8", "D3DDevice_SetTransform");
}

void __stdcall D3DDevice_SetVertexData2f(int a0, float a1, float a2)
{
	wii_unsupported("d3d8", "D3DDevice_SetVertexData2f");
}

void __stdcall D3DDevice_SetVertexData2s(int a0, short a1, short a2)
{
	wii_unsupported("d3d8", "D3DDevice_SetVertexData2s");
}

void __stdcall D3DDevice_SetVertexData4f(int a0, float a1, float a2, float a3, float a4)
{
	wii_unsupported("d3d8", "D3DDevice_SetVertexData4f");
}

void __stdcall D3DDevice_SetVertexData4ub(int a0, unsigned char a1, unsigned char a2, unsigned char a3, unsigned char a4)
{
	wii_unsupported("d3d8", "D3DDevice_SetVertexData4ub");
}

void __stdcall D3DDevice_SetVertexDataColor(int a0, unsigned long a1)
{
	wii_unsupported("d3d8", "D3DDevice_SetVertexDataColor");
}

void __stdcall D3DDevice_SetVertexShader(unsigned long a0)
{
	wii_unsupported("d3d8", "D3DDevice_SetVertexShader");
}

void __stdcall D3DDevice_SetVertexShaderConstant(int a0, const void * a1, unsigned long a2)
{
	wii_unsupported("d3d8", "D3DDevice_SetVertexShaderConstant");
}

void __stdcall D3DDevice_SetVerticalBlankCallback(void (*a0)(unsigned long))
{
	wii_unsupported("d3d8", "D3DDevice_SetVerticalBlankCallback");
}

void __stdcall D3DDevice_SetViewport(const struct _D3DVIEWPORT8 * a0)
{
	wii_unsupported("d3d8", "D3DDevice_SetViewport");
}

void __stdcall D3DPalette_Lock(struct D3DPalette * a0, unsigned long ** a1, unsigned long a2)
{
	wii_unsupported("d3d8", "D3DPalette_Lock");
}

void __stdcall D3DResource_BlockUntilNotBusy(struct D3DResource * a0)
{
	wii_unsupported("d3d8", "D3DResource_BlockUntilNotBusy");
}

int __stdcall D3DResource_IsBusy(struct D3DResource * a0)
{
	wii_unsupported("d3d8", "D3DResource_IsBusy");
	return FALSE;
}

void __stdcall D3DResource_Register(struct D3DResource * a0, void * a1)
{
	wii_unsupported("d3d8", "D3DResource_Register");
}

unsigned long __stdcall D3DResource_Release(struct D3DResource * a0)
{
	wii_unsupported("d3d8", "D3DResource_Release");
	return 0;
}

void __stdcall D3DSurface_GetDesc(struct D3DSurface * a0, struct _D3DSURFACE_DESC * a1)
{
	wii_unsupported("d3d8", "D3DSurface_GetDesc");
}

void __stdcall D3DSurface_LockRect(struct D3DSurface * a0, struct _D3DLOCKED_RECT * a1, const struct tagRECT * a2, unsigned long a3)
{
	wii_unsupported("d3d8", "D3DSurface_LockRect");
}

void __stdcall D3DTexture_GetLevelDesc(struct D3DTexture * a0, unsigned int a1, struct _D3DSURFACE_DESC * a2)
{
	wii_unsupported("d3d8", "D3DTexture_GetLevelDesc");
}

long __stdcall D3DTexture_GetSurfaceLevel(struct D3DTexture * a0, unsigned int a1, struct D3DSurface ** a2)
{
	wii_unsupported("d3d8", "D3DTexture_GetSurfaceLevel");
	return E_FAIL;
}

void __stdcall D3DTexture_LockRect(struct D3DTexture * a0, unsigned int a1, struct _D3DLOCKED_RECT * a2, const struct tagRECT * a3, unsigned long a4)
{
	wii_unsupported("d3d8", "D3DTexture_LockRect");
}

void __stdcall D3DVertexBuffer_Lock(struct D3DVertexBuffer * a0, unsigned int a1, unsigned int a2, unsigned char ** a3, unsigned long a4)
{
	wii_unsupported("d3d8", "D3DVertexBuffer_Lock");
}

void __stdcall D3DVolumeTexture_LockBox(struct D3DVolumeTexture * a0, unsigned int a1, struct _D3DLOCKED_BOX * a2, const struct _D3DBOX * a3, unsigned long a4)
{
	wii_unsupported("d3d8", "D3DVolumeTexture_LockBox");
}

D3DXMATRIX *__stdcall D3DXMatrixOrthoLH(D3DXMATRIX * a0, float a1, float a2, float a3, float a4)
{
	wii_unsupported("d3d8", "D3DXMatrixOrthoLH");
	return NULL;
}

D3DXMATRIX *__stdcall D3DXMatrixPerspectiveLH(D3DXMATRIX * a0, float a1, float a2, float a3, float a4)
{
	wii_unsupported("d3d8", "D3DXMatrixPerspectiveLH");
	return NULL;
}

struct D3DXVECTOR4 *__stdcall D3DXVec4Transform(struct D3DXVECTOR4 * a0, const struct D3DXVECTOR4 * a1, const D3DXMATRIX * a2)
{
	wii_unsupported("d3d8", "D3DXVec4Transform");
	return NULL;
}

struct Direct3D *__stdcall Direct3DCreate8(unsigned int a0)
{
	wii_unsupported("d3d8", "Direct3DCreate8");
	return NULL;
}

long __stdcall Direct3D_CreateDevice(unsigned int a0, enum _D3DDEVTYPE a1, void * a2, unsigned long a3, struct _D3DPRESENT_PARAMETERS_ * a4, struct D3DDevice ** a5)
{
	wii_unsupported("d3d8", "Direct3D_CreateDevice");
	return E_FAIL;
}

void __stdcall Direct3D_SetPushBufferSize(unsigned long a0, unsigned long a1)
{
	wii_unsupported("d3d8", "Direct3D_SetPushBufferSize");
}

/* ---------- dsound */

long __stdcall DirectSoundCreate(struct _GUID * a0, struct IDirectSound ** a1, struct IUnknown * a2)
{
	wii_unsupported("dsound", "DirectSoundCreate");
	return E_FAIL;
}

long __stdcall DirectSoundCreateBuffer(const struct _DSBUFFERDESC * a0, struct IDirectSoundBuffer ** a1)
{
	wii_unsupported("dsound", "DirectSoundCreateBuffer");
	return E_FAIL;
}

void __stdcall DirectSoundDoWork(void)
{
	wii_unsupported("dsound", "DirectSoundDoWork");
}

void __stdcall DirectSoundUseFullHRTF(void)
{
	wii_unsupported("dsound", "DirectSoundUseFullHRTF");
}

long __stdcall IDirectSoundBuffer_Play(struct IDirectSoundBuffer * a0, unsigned long a1, unsigned long a2, unsigned long a3)
{
	wii_unsupported("dsound", "IDirectSoundBuffer_Play");
	return E_FAIL;
}

unsigned long __stdcall IDirectSoundBuffer_Release(struct IDirectSoundBuffer * a0)
{
	wii_unsupported("dsound", "IDirectSoundBuffer_Release");
	return 0;
}

long __stdcall IDirectSoundBuffer_SetBufferData(struct IDirectSoundBuffer * a0, void * a1, unsigned long a2)
{
	wii_unsupported("dsound", "IDirectSoundBuffer_SetBufferData");
	return E_FAIL;
}

long __stdcall IDirectSoundBuffer_SetCurrentPosition(struct IDirectSoundBuffer * a0, unsigned long a1)
{
	wii_unsupported("dsound", "IDirectSoundBuffer_SetCurrentPosition");
	return E_FAIL;
}

long __stdcall IDirectSoundBuffer_SetLoopRegion(struct IDirectSoundBuffer * a0, unsigned long a1, unsigned long a2)
{
	wii_unsupported("dsound", "IDirectSoundBuffer_SetLoopRegion");
	return E_FAIL;
}

long __stdcall IDirectSoundBuffer_SetPitch(struct IDirectSoundBuffer * a0, long a1)
{
	wii_unsupported("dsound", "IDirectSoundBuffer_SetPitch");
	return E_FAIL;
}

long __stdcall IDirectSoundBuffer_SetVolume(struct IDirectSoundBuffer * a0, long a1)
{
	wii_unsupported("dsound", "IDirectSoundBuffer_SetVolume");
	return E_FAIL;
}

long __stdcall IDirectSoundBuffer_Stop(struct IDirectSoundBuffer * a0)
{
	wii_unsupported("dsound", "IDirectSoundBuffer_Stop");
	return E_FAIL;
}

long __stdcall IDirectSoundStream_SetConeAngles(struct IDirectSoundStream * a0, unsigned long a1, unsigned long a2, unsigned long a3)
{
	wii_unsupported("dsound", "IDirectSoundStream_SetConeAngles");
	return E_FAIL;
}

long __stdcall IDirectSoundStream_SetConeOrientation(struct IDirectSoundStream * a0, float a1, float a2, float a3, unsigned long a4)
{
	wii_unsupported("dsound", "IDirectSoundStream_SetConeOrientation");
	return E_FAIL;
}

long __stdcall IDirectSoundStream_SetConeOutsideVolume(struct IDirectSoundStream * a0, long a1, unsigned long a2)
{
	wii_unsupported("dsound", "IDirectSoundStream_SetConeOutsideVolume");
	return E_FAIL;
}

long __stdcall IDirectSoundStream_SetFrequency(struct IDirectSoundStream * a0, unsigned long a1)
{
	wii_unsupported("dsound", "IDirectSoundStream_SetFrequency");
	return E_FAIL;
}

long __stdcall IDirectSoundStream_SetI3DL2Source(struct IDirectSoundStream * a0, const struct _DSI3DL2BUFFER * a1, unsigned long a2)
{
	wii_unsupported("dsound", "IDirectSoundStream_SetI3DL2Source");
	return E_FAIL;
}

long __stdcall IDirectSoundStream_SetMaxDistance(struct IDirectSoundStream * a0, float a1, unsigned long a2)
{
	wii_unsupported("dsound", "IDirectSoundStream_SetMaxDistance");
	return E_FAIL;
}

long __stdcall IDirectSoundStream_SetMinDistance(struct IDirectSoundStream * a0, float a1, unsigned long a2)
{
	wii_unsupported("dsound", "IDirectSoundStream_SetMinDistance");
	return E_FAIL;
}

long __stdcall IDirectSoundStream_SetMixBinVolumes(struct IDirectSoundStream * a0, unsigned long a1, const long * a2)
{
	wii_unsupported("dsound", "IDirectSoundStream_SetMixBinVolumes");
	return E_FAIL;
}

long __stdcall IDirectSoundStream_SetMixBins(struct IDirectSoundStream * a0, unsigned long a1)
{
	wii_unsupported("dsound", "IDirectSoundStream_SetMixBins");
	return E_FAIL;
}

long __stdcall IDirectSoundStream_SetMode(struct IDirectSoundStream * a0, unsigned long a1, unsigned long a2)
{
	wii_unsupported("dsound", "IDirectSoundStream_SetMode");
	return E_FAIL;
}

long __stdcall IDirectSoundStream_SetPosition(struct IDirectSoundStream * a0, float a1, float a2, float a3, unsigned long a4)
{
	wii_unsupported("dsound", "IDirectSoundStream_SetPosition");
	return E_FAIL;
}

long __stdcall IDirectSoundStream_SetVelocity(struct IDirectSoundStream * a0, float a1, float a2, float a3, unsigned long a4)
{
	wii_unsupported("dsound", "IDirectSoundStream_SetVelocity");
	return E_FAIL;
}

long __stdcall IDirectSoundStream_SetVolume(struct IDirectSoundStream * a0, long a1)
{
	wii_unsupported("dsound", "IDirectSoundStream_SetVolume");
	return E_FAIL;
}

long __stdcall IDirectSound_CommitDeferredSettings(struct IDirectSound * a0)
{
	wii_unsupported("dsound", "IDirectSound_CommitDeferredSettings");
	return E_FAIL;
}

long __stdcall IDirectSound_CreateSoundBuffer(struct IDirectSound * a0, const struct _DSBUFFERDESC * a1, struct IDirectSoundBuffer ** a2, struct IUnknown * a3)
{
	wii_unsupported("dsound", "IDirectSound_CreateSoundBuffer");
	return E_FAIL;
}

long __stdcall IDirectSound_CreateSoundStream(struct IDirectSound * a0, const struct _DSSTREAMDESC * a1, struct IDirectSoundStream ** a2, struct IUnknown * a3)
{
	wii_unsupported("dsound", "IDirectSound_CreateSoundStream");
	return E_FAIL;
}

long __stdcall IDirectSound_DownloadEffectsImage(struct IDirectSound * a0, const void * a1, unsigned long a2, const struct _DSEFFECTIMAGELOC * a3, struct _DSEFFECTIMAGEDESC ** a4)
{
	wii_unsupported("dsound", "IDirectSound_DownloadEffectsImage");
	return E_FAIL;
}

long __stdcall IDirectSound_GetCaps(struct IDirectSound * a0, struct _DSCAPS * a1)
{
	wii_unsupported("dsound", "IDirectSound_GetCaps");
	return E_FAIL;
}

long __stdcall IDirectSound_GetSpeakerConfig(struct IDirectSound * a0, unsigned long * a1)
{
	wii_unsupported("dsound", "IDirectSound_GetSpeakerConfig");
	return E_FAIL;
}

unsigned long __stdcall IDirectSound_Release(struct IDirectSound * a0)
{
	wii_unsupported("dsound", "IDirectSound_Release");
	return 0;
}

long __stdcall IDirectSound_SetDistanceFactor(struct IDirectSound * a0, float a1, unsigned long a2)
{
	wii_unsupported("dsound", "IDirectSound_SetDistanceFactor");
	return E_FAIL;
}

long __stdcall IDirectSound_SetI3DL2Listener(struct IDirectSound * a0, const struct _DSI3DL2LISTENER * a1, unsigned long a2)
{
	wii_unsupported("dsound", "IDirectSound_SetI3DL2Listener");
	return E_FAIL;
}

long __stdcall IDirectSound_SetMixBinHeadroom(struct IDirectSound * a0, unsigned long a1, unsigned long a2)
{
	wii_unsupported("dsound", "IDirectSound_SetMixBinHeadroom");
	return E_FAIL;
}

long __stdcall IDirectSound_SetOrientation(struct IDirectSound * a0, float a1, float a2, float a3, float a4, float a5, float a6, unsigned long a7)
{
	wii_unsupported("dsound", "IDirectSound_SetOrientation");
	return E_FAIL;
}

long __stdcall IDirectSound_SetPosition(struct IDirectSound * a0, float a1, float a2, float a3, unsigned long a4)
{
	wii_unsupported("dsound", "IDirectSound_SetPosition");
	return E_FAIL;
}

long __stdcall IDirectSound_SetRolloffFactor(struct IDirectSound * a0, float a1, unsigned long a2)
{
	wii_unsupported("dsound", "IDirectSound_SetRolloffFactor");
	return E_FAIL;
}

long __stdcall IDirectSound_SetVelocity(struct IDirectSound * a0, float a1, float a2, float a3, unsigned long a4)
{
	wii_unsupported("dsound", "IDirectSound_SetVelocity");
	return E_FAIL;
}

/* ---------- input */

int __stdcall XGetDeviceChanges(struct _XPP_DEVICE_TYPE * a0, unsigned long * a1, unsigned long * a2)
{
	wii_unsupported("input", "XGetDeviceChanges");
	return 0;
}

void __stdcall XInitDevices(unsigned long a0, struct _XDEVICE_PREALLOC_TYPE * a1)
{
	wii_unsupported("input", "XInitDevices");
}

void __stdcall XInputClose(void * a0)
{
	wii_unsupported("input", "XInputClose");
}

unsigned long __stdcall XInputDebugGetKeystroke(struct _XINPUT_DEBUG_KEYSTROKE * a0)
{
	wii_unsupported("input", "XInputDebugGetKeystroke");
	return ERROR_DEVICE_NOT_CONNECTED;
}

unsigned long __stdcall XInputDebugInitKeyboardQueue(struct _XINPUT_DEBUG_KEYQUEUE_PARAMETERS * a0)
{
	wii_unsupported("input", "XInputDebugInitKeyboardQueue");
	return ERROR_DEVICE_NOT_CONNECTED;
}

unsigned long __stdcall XInputGetState(void * a0, struct _XINPUT_STATE * a1)
{
	wii_unsupported("input", "XInputGetState");
	return ERROR_DEVICE_NOT_CONNECTED;
}

void *__stdcall XInputOpen(struct _XPP_DEVICE_TYPE * a0, unsigned long a1, unsigned long a2, struct _XINPUT_POLLING_PARAMETERS * a3)
{
	wii_unsupported("input", "XInputOpen");
	return NULL;
}

unsigned long __stdcall XInputSetState(void * a0, struct _XINPUT_FEEDBACK * a1)
{
	wii_unsupported("input", "XInputSetState");
	return ERROR_DEVICE_NOT_CONNECTED;
}

/* ---------- network */

int __stdcall WSACleanup(void)
{
	wii_unsupported("network", "WSACleanup");
	return SOCKET_ERROR;
}

int __stdcall WSAGetLastError(void)
{
	wii_unsupported("network", "WSAGetLastError");
	return WSASYSNOTREADY;
}

int __stdcall WSAStartup(unsigned short a0, struct WSAData * a1)
{
	wii_unsupported("network", "WSAStartup");
	return WSASYSNOTREADY;
}

int __stdcall XNetCleanup(void)
{
	wii_unsupported("network", "XNetCleanup");
	return WSASYSNOTREADY;
}

int __stdcall XNetCreateKey(struct XNKID * a0, struct XNKEY * a1)
{
	wii_unsupported("network", "XNetCreateKey");
	return WSASYSNOTREADY;
}

unsigned long __stdcall XNetGetEthernetLinkStatus(void)
{
	wii_unsupported("network", "XNetGetEthernetLinkStatus");
	return 0;
}

unsigned long __stdcall XNetGetTitleXnAddr(struct XNADDR * a0)
{
	wii_unsupported("network", "XNetGetTitleXnAddr");
	return XNET_GET_XNADDR_NONE;
}

int __stdcall XNetRandom(unsigned char * a0, unsigned int a1)
{
	wii_unsupported("network", "XNetRandom");
	return WSASYSNOTREADY;
}

int __stdcall XNetRegisterKey(const struct XNKID * a0, const struct XNKEY * a1)
{
	wii_unsupported("network", "XNetRegisterKey");
	return WSASYSNOTREADY;
}

int __stdcall XNetStartup(const struct XNetStartupParams * a0)
{
	wii_unsupported("network", "XNetStartup");
	return WSASYSNOTREADY;
}

int __stdcall XNetUnregisterKey(const struct XNKID * a0)
{
	wii_unsupported("network", "XNetUnregisterKey");
	return WSASYSNOTREADY;
}

int __stdcall XNetXnAddrToInAddr(const struct XNADDR * a0, const struct XNKID * a1, struct in_addr * a2)
{
	wii_unsupported("network", "XNetXnAddrToInAddr");
	return WSASYSNOTREADY;
}

int __stdcall __WSAFDIsSet(unsigned int a0, struct halo_ws_fd_set * a1)
{
	wii_unsupported("network", "__WSAFDIsSet");
	return 0;
}

unsigned int __stdcall halo_ws_accept(unsigned int a0, struct sockaddr * a1, int * a2)
{
	wii_unsupported("network", "halo_ws_accept");
	return INVALID_SOCKET;
}

int __stdcall halo_ws_bind(unsigned int a0, const struct sockaddr * a1, int a2)
{
	wii_unsupported("network", "halo_ws_bind");
	return SOCKET_ERROR;
}

int __stdcall halo_ws_closesocket(unsigned int a0)
{
	wii_unsupported("network", "halo_ws_closesocket");
	return SOCKET_ERROR;
}

int __stdcall halo_ws_connect(unsigned int a0, const struct sockaddr * a1, int a2)
{
	wii_unsupported("network", "halo_ws_connect");
	return SOCKET_ERROR;
}

int __stdcall halo_ws_getpeername(unsigned int a0, struct sockaddr * a1, int * a2)
{
	wii_unsupported("network", "halo_ws_getpeername");
	return SOCKET_ERROR;
}

int __stdcall halo_ws_getsockname(unsigned int a0, struct sockaddr * a1, int * a2)
{
	wii_unsupported("network", "halo_ws_getsockname");
	return SOCKET_ERROR;
}

int __stdcall halo_ws_getsockopt(unsigned int a0, int a1, int a2, char * a3, int * a4)
{
	wii_unsupported("network", "halo_ws_getsockopt");
	return SOCKET_ERROR;
}

int __stdcall halo_ws_ioctlsocket(unsigned int a0, long a1, unsigned long * a2)
{
	wii_unsupported("network", "halo_ws_ioctlsocket");
	return SOCKET_ERROR;
}

int __stdcall halo_ws_listen(unsigned int a0, int a1)
{
	wii_unsupported("network", "halo_ws_listen");
	return SOCKET_ERROR;
}

int __stdcall halo_ws_recv(unsigned int a0, char * a1, int a2, int a3)
{
	wii_unsupported("network", "halo_ws_recv");
	return SOCKET_ERROR;
}

int __stdcall halo_ws_recvfrom(unsigned int a0, char * a1, int a2, int a3, struct sockaddr * a4, int * a5)
{
	wii_unsupported("network", "halo_ws_recvfrom");
	return SOCKET_ERROR;
}

int __stdcall halo_ws_select(int a0, struct halo_ws_fd_set * a1, struct halo_ws_fd_set * a2, struct halo_ws_fd_set * a3, const struct halo_ws_timeval * a4)
{
	wii_unsupported("network", "halo_ws_select");
	return SOCKET_ERROR;
}

int __stdcall halo_ws_send(unsigned int a0, const char * a1, int a2, int a3)
{
	wii_unsupported("network", "halo_ws_send");
	return SOCKET_ERROR;
}

int __stdcall halo_ws_sendto(unsigned int a0, const char * a1, int a2, int a3, const struct sockaddr * a4, int a5)
{
	wii_unsupported("network", "halo_ws_sendto");
	return SOCKET_ERROR;
}

int __stdcall halo_ws_setsockopt(unsigned int a0, int a1, int a2, const char * a3, int a4)
{
	wii_unsupported("network", "halo_ws_setsockopt");
	return SOCKET_ERROR;
}

unsigned int __stdcall halo_ws_socket(int a0, int a1, int a2)
{
	wii_unsupported("network", "halo_ws_socket");
	return INVALID_SOCKET;
}

/* ---------- xbdm */

HRESULT __stdcall DmCloseModuleSections(PDM_WALK_MODSECT walk)
{
	wii_unsupported("xbdm", "DmCloseModuleSections");
	return E_FAIL;
}

HRESULT __stdcall DmWalkLoadedModules(PDM_WALK_MODULES *walk, PDMN_MODLOAD module)
{
	wii_unsupported("xbdm", "DmWalkLoadedModules");
	return XBDM_ENDOFLIST;
}

HRESULT __stdcall DmWalkModuleSections(PDM_WALK_MODSECT *walk, const char *module_name, PDMN_SECTIONLOAD section)
{
	wii_unsupported("xbdm", "DmWalkModuleSections");
	return XBDM_ENDOFLIST;
}
