#ifndef WII_CACHE_SCHEMA_TABLES_H
#define WII_CACHE_SCHEMA_TABLES_H
#include <stdint.h>

/* The upstream tag validator's schema (port/linux/game/tag_schema.h) as plain
 * data, generated by tools/wii/export_tag_schema.py on the upstream i686 ABI.
 * Offsets/sizes are the Xbox cache layout; nothing here is a native pointer. */

enum cache_schema_type {
    CACHE_SCHEMA_BLOCK, CACHE_SCHEMA_DATA, CACHE_SCHEMA_FILE_DATA, CACHE_SCHEMA_REFERENCE,
    CACHE_SCHEMA_TAG_INDEX, CACHE_SCHEMA_BLOCK_INDEX, CACHE_SCHEMA_ENUM, CACHE_SCHEMA_STRING,
    CACHE_SCHEMA_RESET, CACHE_SCHEMA_STRUCT, CACHE_SCHEMA_CHECK, CACHE_SCHEMA_TYPE_COUNT
};
enum { CACHE_SCHEMA_NONE_BIT = 1, CACHE_SCHEMA_UNSIGNED_BIT = 2 };
enum { CACHE_SCHEMA_ROOT = -1, CACHE_SCHEMA_STRUCTURE = -2 };

struct cache_schema_field {
    int16_t type, flags, size, count;
    int32_t offset, maximum, target_level, target_offset;
    /* block/struct: definition index; reference/tag index: group-list word offset (-1: any) */
    int32_t link;
};
struct cache_schema_definition { int32_t size, first_field, field_count; };
struct cache_schema_group { uint32_t group_tag, parent_group_tags[2]; int32_t definition; };
/* a pointer field a schema check reads rather than a typed field (model part and bsp material buffers) */
struct cache_schema_pointer { int32_t definition, offset; };
struct cache_schema_counts { int32_t fields, definitions, group_list_words, groups, pointers; };

extern const struct cache_schema_field cache_schema_fields[];
extern const struct cache_schema_definition cache_schema_definitions[];
extern const uint32_t cache_schema_group_lists[];
extern const struct cache_schema_group cache_schema_groups[];
extern const struct cache_schema_pointer cache_schema_pointers[];
extern const struct cache_schema_counts cache_schema_counts;
#endif
