"""Build an isolated tag-index diagnostic, optionally with PRIVATE input bytes.

Output must be ignored by Git. Private bytes and binaries must never be shared.
The default diagnostic contains only authored synthetic fixtures.
"""
import argparse
import hashlib
import json
import os
import re
from pathlib import Path
import struct
import subprocess
import zlib
from build import verify_dol, verify_elf
from check_toolchain import inspect_toolchain, toolchain_inputs


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--cc', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True)
    parser.add_argument('--wii-devkitpro', type=Path)
    parser.add_argument('--private-tag-data', type=Path)
    parser.add_argument('--stream-file', help='stream tag bytes from this sd:/ path instead of embedding them')
    parser.add_argument('--widget-goldens', type=Path, help='external numeric goldens for a representative typed widget graph')
    parser.add_argument('--widget-fixture', action='store_true', help='run authored widget cases without private input')
    parser.add_argument('--bsp-goldens', type=Path, help='external numeric goldens for a bounded BSP residency view')
    parser.add_argument('--private-bsp-data', type=Path, help='external raw BSP bytes used only for numeric build goldens')
    parser.add_argument('--bsp-stream-file', help='safe sd:/ path for the private raw BSP sidecar')
    parser.add_argument('--bsp-fixture', action='store_true', help='run authored BSP residency cases without private input')
    parser.add_argument('--material-fixture', action='store_true', help='run authored partial material graph cases without private input')
    args = parser.parse_args()
    if args.stream_file and (not args.private_tag_data or not re.fullmatch(r'sd:/[A-Za-z0-9_/.-]+', args.stream_file)
                             or '..' in args.stream_file.split('/')):
        parser.error('--stream-file requires private tag goldens and a safe sd:/ path')
    if args.widget_goldens and not args.stream_file:
        parser.error('--widget-goldens requires --stream-file')
    if args.widget_fixture and (args.private_tag_data or args.stream_file or args.widget_goldens):
        parser.error('--widget-fixture runs without private input or streaming arguments')
    bsp_arguments = (args.bsp_goldens, args.private_bsp_data, args.bsp_stream_file)
    if any(bsp_arguments) and (not all(bsp_arguments) or not args.stream_file):
        parser.error('BSP streaming requires --bsp-goldens, --private-bsp-data, --bsp-stream-file and --stream-file')
    if args.bsp_stream_file and (not re.fullmatch(r'sd:/[A-Za-z0-9_/.-]+', args.bsp_stream_file)
                                or '..' in args.bsp_stream_file.split('/')):
        parser.error('--bsp-stream-file must be a safe sd:/ path')
    if args.bsp_fixture and (args.private_tag_data or args.stream_file or args.widget_goldens or
                            args.widget_fixture or any(bsp_arguments)):
        parser.error('--bsp-fixture runs alone without private input or streaming arguments')
    if args.widget_fixture and any(bsp_arguments):
        parser.error('--widget-fixture cannot use BSP streaming arguments')
    if args.material_fixture and (args.private_tag_data or args.stream_file or args.widget_goldens or
                                 args.widget_fixture or args.bsp_fixture or any(bsp_arguments)):
        parser.error('--material-fixture runs alone without private input or streaming arguments')
    root = Path.cwd().resolve()
    output = args.output.resolve()
    if not output.is_relative_to(root) or output == root:
        parser.error('output must be an ignored subdirectory of this checkout')
    ignored = subprocess.run(['git', 'check-ignore', '--quiet', str(output) + os.sep])
    if ignored.returncode != 0:
        parser.error('output must be ignored by Git before any generated bytes are written')
    if output.exists():
        parser.error('new output directory required; existing evidence is preserved')
    compiler = args.cc.resolve(strict=True)
    environment = os.environ.copy()
    overrides = ('GCC_EXEC_PREFIX', 'COMPILER_PATH', 'LIBRARY_PATH', 'CPATH', 'C_INCLUDE_PATH',
                 'CPLUS_INCLUDE_PATH', 'OBJC_INCLUDE_PATH', 'DEPENDENCIES_OUTPUT', 'SUNPRO_DEPENDENCIES')
    for name in overrides:
        environment.pop(name, None)
    environment['PATH'] = str(compiler.parent) + os.pathsep + environment.get('PATH', '')
    target = subprocess.check_output([str(compiler), '-dumpmachine'], env=environment, text=True).strip()
    if (target == 'powerpc-eabi') != bool(args.wii_devkitpro):
        parser.error('PowerPC requires --wii-devkitpro; host compiler must omit it')
    names = ['cache_address_probe.c', 'cache_address_fixture.c', 'cache_address_owned.c']
    names += (['cache_arena_plan.c', 'cache_arena_fixture.c', 'cache_stream_io.c', 'cache_stream_fixture.c',
               'cache_stream_main.c'] if args.stream_file else ['cache_address_main.c'])
    if args.widget_goldens or args.widget_fixture:
        names += ['cache_widget_probe.c', 'cache_widget_fixture.c']
    if args.widget_fixture:
        names += ['cache_arena_plan.c']
    if args.bsp_goldens or args.bsp_fixture:
        names += ['cache_bsp_probe.c', 'cache_bsp_fixture.c']
    if args.bsp_fixture:
        names += ['cache_arena_plan.c']
    if args.material_fixture:
        names += ['cache_arena_plan.c', 'cache_bsp_probe.c', 'cache_material_probe.c',
                  'cache_material_fixture.c']
    sources = [Path('tools/wii')/name for name in names]
    inputs = sources + [Path('tools/wii')/name for name in ('cache_address_probe.h', 'cache_address_fixture.h',
                                                          'cache_address_owned.h', 'run_cache_address.py',
                                                          'build.py', 'check_toolchain.py')]
    inputs += [Path('source/cache/cache_files.c'), Path('source/cache/physical_memory_map.c'),
               Path('source/cache/physical_memory_map.h'), Path('port/linux/include/halo_port_capacity.h')]
    if args.stream_file:
        inputs += [Path('tools/wii')/name for name in ('cache_arena_plan.h', 'cache_arena_fixture.h',
                                                     'cache_stream_io.h', 'cache_stream_fixture.h')]
    if args.widget_goldens or args.widget_fixture:
        inputs += [Path('tools/wii')/name for name in ('cache_widget_probe.h', 'cache_widget_fixture.h')]
        inputs += [Path('source/interface/ui_widget.c'), Path('source/tag_files/tag_groups.h'),
                   Path('source/math/integer_math.h'), Path('source/math/real_math.h'),
                   Path('port/linux/game/tag_schema_effects.c'), Path('port/linux/game/tag_validate.c')]
    if args.widget_goldens:
        inputs += [Path('tools/wii/inspect_widget_graph.py')]
    if args.widget_fixture:
        inputs += [Path('tools/wii/cache_arena_plan.h')]
    if args.bsp_goldens or args.bsp_fixture:
        inputs += [Path('tools/wii')/name for name in ('cache_bsp_probe.h', 'cache_bsp_fixture.h')]
        inputs += [Path('source/scenario/scenario.h'), Path('source/scenario/scenario_definitions.h'),
                   Path('port/linux/game/tag_schema_scenario.c'), Path('port/linux/game/cache_file_formats.c'),
                   Path('source/structures/structure_bsp_definitions.h'), Path('port/linux/game/tag_validate.c')]
    if args.bsp_fixture:
        inputs += [Path('tools/wii/cache_arena_plan.h')]
    if args.bsp_goldens:
        inputs += [Path('tools/wii/inspect_bsp_residency.py'), Path('tools/wii/inspect_widget_graph.py')]
    if args.material_fixture:
        inputs += [Path('tools/wii')/name for name in ('cache_arena_plan.h', 'cache_bsp_probe.h',
                                                     'cache_material_probe.h', 'cache_material_fixture.h')]
        inputs += [Path('source/scenario/scenario.h'), Path('source/scenario/scenario_definitions.h'),
                   Path('source/structures/structure_bsp_definitions.h'), Path('source/structures/structures.h'),
                   Path('source/rasterizer/rasterizer_geometry.h'), Path('source/tag_files/tag_groups.h'),
                   Path('port/linux/game/cache_file_formats.c'), Path('port/linux/game/tag_schema_scenario.c'),
                   Path('port/linux/game/tag_schema_collision.c'), Path('port/linux/game/tag_validate.c')]
    hashes = {p.as_posix(): hashlib.sha256(p.read_bytes()).hexdigest() for p in inputs}
    source_commit = subprocess.check_output(['git', 'rev-parse', 'HEAD'], text=True).strip()
    dirty = bool(subprocess.check_output(['git', 'status', '--porcelain', '--', *map(str, inputs)], text=True))
    payload = b''
    count = table_crc = 0
    widget_goldens = None
    widget_metadata_sha256 = None
    bsp_goldens = None
    bsp_payload = b''
    bsp_metadata_sha256 = None
    if args.private_tag_data:
        private_path = args.private_tag_data.resolve(strict=True)
        if private_path.is_relative_to(root):
            parser.error('private source data must stay outside the repository')
        if not 36 <= private_path.stat().st_size <= 0x1600000:
            parser.error('private tag blob must be 36 bytes to 22 MiB')
        payload = private_path.read_bytes()
        address, _, _, count = struct.unpack_from('<4I', payload)
        offset = address - 0x803A6000
        if not 1 <= count <= 65535 or offset < 36 or offset > len(payload) - count * 32:
            parser.error('private index table extent invalid')
        table_crc = zlib.crc32(payload[offset:offset + count * 32])
    if args.widget_goldens:
        metadata = args.widget_goldens.resolve(strict=True)
        if metadata.is_relative_to(root) or not 1 <= metadata.stat().st_size <= 1048576:
            parser.error('widget metadata must be a bounded external private file')
        metadata_bytes = metadata.read_bytes()
        widget_metadata_sha256 = hashlib.sha256(metadata_bytes).hexdigest()
        inspection = json.loads(metadata_bytes)
        if inspection['input_sha256'] != hashlib.sha256(payload).hexdigest():
            parser.error('widget metadata belongs to another private tag input')
        widget_goldens = inspection['goldens']
        for key in ('root_datum', 'node_count', 'serialized_bytes', 'serialized_crc32'):
            value = widget_goldens[key]
            if type(value) is not int or not 0 <= value <= 0xffffffff:
                parser.error('widget golden must be an unsigned 32-bit integer: ' + key)
        if (not 1 <= widget_goldens['node_count'] <= count or
                not 1 <= widget_goldens['serialized_bytes'] <= len(payload)):
            parser.error('representative widget golden extents invalid')
    if args.bsp_goldens:
        private_bsp = args.private_bsp_data.resolve(strict=True)
        metadata = args.bsp_goldens.resolve(strict=True)
        if (private_bsp.is_relative_to(root) or metadata.is_relative_to(root) or
                not 24 <= private_bsp.stat().st_size <= 0x1600000 or
                not 1 <= metadata.stat().st_size <= 1048576):
            parser.error('BSP data/metadata must be bounded external private files')
        bsp_payload = private_bsp.read_bytes()
        metadata_bytes = metadata.read_bytes()
        bsp_metadata_sha256 = hashlib.sha256(metadata_bytes).hexdigest()
        inspection = json.loads(metadata_bytes)
        if (inspection['tag_input_sha256'] != hashlib.sha256(payload).hexdigest() or
                inspection['bsp_input_sha256'] != hashlib.sha256(bsp_payload).hexdigest()):
            parser.error('BSP metadata belongs to different private input')
        bsp_goldens = inspection['goldens']
        for key in ('scenario_datum', 'datum', 'bsp_ordinal', 'encoded_base', 'root_address',
                    'root_offset', 'declared_map_bytes', 'file_bytes', 'rounded_reservation_bytes',
                    'vertex_count', 'index_count', 'serialized_bytes', 'serialized_crc32'):
            value = bsp_goldens[key]
            if type(value) is not int or not 0 <= value <= 0xffffffff:
                parser.error('BSP golden must be an unsigned 32-bit integer: ' + key)
        if (bsp_goldens['bsp_ordinal'] >= 16 or bsp_goldens['file_bytes'] != len(bsp_payload) or
                bsp_goldens['serialized_bytes'] != len(bsp_payload) or
                bsp_goldens['serialized_crc32'] != zlib.crc32(bsp_payload) or
                bsp_goldens['rounded_reservation_bytes'] != ((len(bsp_payload) + 511) & ~511) or
                not 2048 <= bsp_goldens['declared_map_bytes'] <= 0x11600000 or
                bsp_goldens['encoded_base'] < 0x803a6000 or
                bsp_goldens['encoded_base'] - 0x803a6000 > 0x1600000 - bsp_goldens['rounded_reservation_bytes']):
            parser.error('representative BSP golden extents invalid')
    sdk_identity = {}
    inventory = None
    if args.wii_devkitpro:
        sdk = args.wii_devkitpro.resolve(strict=True)
        inventory = inspect_toolchain(sdk)
        if inventory['errors']:
            raise ValueError('Wii preflight failed: ' + '; '.join(inventory['errors']))
        if compiler != Path(inventory['tools']['powerpc-eabi-gcc']['path']).resolve():
            parser.error('compiler does not belong to selected SDK')
        fingerprint = hashlib.sha256()
        for p in toolchain_inputs(sdk):
            fingerprint.update(p.relative_to(sdk).as_posix().encode() + b'\0')
            if p.is_file():
                fingerprint.update(hashlib.sha256(p.read_bytes()).digest())
        sdk_identity['toolchain_tree_sha256'] = fingerprint.hexdigest()
    record = {'scope':'isolated_xbox_index_address_diagnostic_not_engine_conversion',
              'source_commit':source_commit, 'source_dirty':dirty, 'inputs_sha256':hashes,
              'private_input_bytes':len(payload), 'private_input_sha256':hashlib.sha256(payload).hexdigest() if payload else None,
              'private_input_crc32':zlib.crc32(payload), 'private_tag_count':count, 'private_table_crc32':table_crc,
              'compiler':subprocess.check_output([str(compiler), '--version'], env=environment, text=True).splitlines()[0],
              'compiler_sha256':hashlib.sha256(compiler.read_bytes()).hexdigest(), 'target':target,
              'cleared_child_environment_overrides':list(overrides), 'sdk_identity':sdk_identity,
              'commands':[], 'state':'incomplete'}
    record['private_input_embedded'] = bool(payload) and not args.stream_file
    record['stream_file'] = args.stream_file
    if args.widget_goldens:
        record['scope'] = 'representative_partial_typed_widget_graph_not_engine_conversion'
        record['widget_goldens'] = widget_goldens
        record['widget_metadata_sha256'] = widget_metadata_sha256
    if args.widget_fixture:
        record['scope'] = 'authored_partial_widget_graph_fixture_no_private_input'
    if args.bsp_goldens:
        record['scope'] = 'bounded_BSP_header_root_residency_not_geometry_conversion'
        record['bsp_goldens'] = bsp_goldens
        record['bsp_metadata_sha256'] = bsp_metadata_sha256
        record['private_bsp_bytes'] = len(bsp_payload)
        record['private_bsp_sha256'] = hashlib.sha256(bsp_payload).hexdigest()
        record['private_bsp_crc32'] = zlib.crc32(bsp_payload)
        record['bsp_stream_file'] = args.bsp_stream_file
    if args.bsp_fixture:
        record['scope'] = 'authored_BSP_residency_fixture_no_private_input'
    if args.material_fixture:
        record['scope'] = 'authored_partial_material_graph_fixture_no_private_input'
    build_id = hashlib.sha256(json.dumps(record, sort_keys=True).encode()).hexdigest()[:16]
    record['build_id'] = build_id
    output.mkdir(parents=True)
    record_path = output/'cache-info.json'
    def save():
        record_path.write_text(json.dumps(record, indent=2)+'\n', encoding='utf-8')
    save()
    header = output/'cache_probe_payload.h'
    with header.open('w', encoding='ascii') as stream:
        stream.write(f'#define CACHE_PROBE_BUILD_ID "{build_id}"\n#define CACHE_PRIVATE_SIZE {len(payload)}\n')
        stream.write(f'#define CACHE_PRIVATE_CRC {zlib.crc32(payload)}u\n#define CACHE_PRIVATE_COUNT {count}u\n')
        stream.write(f'#define CACHE_PRIVATE_TABLE_CRC {table_crc}u\n')
        if args.stream_file:
            stream.write('#define CACHE_STREAM_FILENAME '+json.dumps(args.stream_file)+'\n')
        if args.widget_goldens:
            stream.write('#define CACHE_WIDGET_GRAPH 1\n')
            for key in ('root_datum', 'node_count', 'serialized_bytes', 'serialized_crc32'):
                stream.write('#define CACHE_WIDGET_'+key.upper()+' '+str(widget_goldens[key])+'u\n')
        if args.widget_fixture:
            stream.write('#define CACHE_WIDGET_FIXTURE 1\n')
        if args.bsp_goldens:
            stream.write('#define CACHE_BSP_RESIDENCY 1\n')
            stream.write('#define CACHE_BSP_FILENAME '+json.dumps(args.bsp_stream_file)+'\n')
            for key in ('scenario_datum', 'datum', 'bsp_ordinal', 'encoded_base', 'root_address',
                        'root_offset', 'declared_map_bytes', 'file_bytes', 'rounded_reservation_bytes',
                        'vertex_count', 'index_count', 'serialized_bytes', 'serialized_crc32'):
                stream.write('#define CACHE_BSP_GOLDEN_'+key.upper()+' '+str(bsp_goldens[key])+'u\n')
        if args.bsp_fixture:
            stream.write('#define CACHE_BSP_FIXTURE 1\n')
        if args.material_fixture:
            stream.write('#define CACHE_MATERIAL_FIXTURE 1\n')
        if payload and not args.stream_file:
            stream.write('static const unsigned char cache_private_bytes[] = {\n')
            for i in range(0, len(payload), 24):
                stream.write(','.join(str(b) for b in payload[i:i+24])+',\n')
            stream.write('};\n')
    flags = ['-std=c11', '-O2', '-Wall', '-Wextra', '-Werror', '-fstack-usage', '-I', 'tools/wii', '-I', str(output)]
    if inventory:
        flags += ['-DGEKKO', '-mrvl', '-mcpu=750', '-meabi', '-mhard-float', '-I', str(sdk/'libogc/include')]
    record['flags'] = flags
    def run(argv):
        p = subprocess.run(argv, env=environment, capture_output=True, text=True)
        record['commands'].append({'arguments':argv, 'exit_code':p.returncode, 'stdout':p.stdout.splitlines(),
                                   'stderr':p.stderr.splitlines()})
        save()
        if p.stdout: print(p.stdout, end='')
        if p.stderr: print(p.stderr, end='', file=__import__('sys').stderr)
        p.check_returncode()
        return p
    objects = []
    for source in sources:
        obj = output/(source.stem+'.o')
        run([str(compiler), *flags, '-c', str(source), '-o', str(obj)])
        objects.append(str(obj))
    if inventory:
        elf, dol = output/'cache_address.elf', output/'cache_address.dol'
        run([str(compiler), *objects, '-mrvl', '-mcpu=750', '-meabi', '-mhard-float',
             '-Wl,-Map,'+str(output/'cache_address.map'), '-L', str(sdk/'libogc/lib/wii'),
             '-lfat', '-logc', '-lm', '-o', str(elf)])
        record['elf'] = verify_elf(elf)
        run([inventory['tools']['elf2dol']['path'], str(elf), str(dol)])
        verify_dol(dol)
        record['state'] = 'compile_pass'
    else:
        exe = output/('cache_address.exe' if os.name == 'nt' else 'cache_address')
        run([str(compiler), *objects, '-o', str(exe)])
        execution = [str(exe)]
        if args.stream_file:
            execution += [str(args.private_tag_data.resolve())]
        if args.bsp_goldens:
            execution += [str(args.private_bsp_data.resolve())]
        executed = run(execution)
        record['report'] = executed.stdout.splitlines()
        record['state'] = 'execution_pass'
    record['artifacts_sha256'] = {p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in output.iterdir()
                                 if p.name == 'cache_address' or p.suffix in ('.o', '.su', '.exe', '.elf', '.dol', '.map')}
    record['generated_payload_sha256'] = hashlib.sha256(header.read_bytes()).hexdigest()
    save()
    print(f'Cache address diagnostic build={build_id} state={record["state"]}')


if __name__ == '__main__':
    main()
