"""Build an isolated tag-index diagnostic, optionally with PRIVATE input bytes.

Output must be ignored by Git. Private bytes and binaries must never be shared.
The default diagnostic contains only authored synthetic fixtures.
"""
import argparse
import hashlib
import json
import os
from pathlib import Path
import struct
import subprocess
import zlib
from build import verify_dol, verify_elf
from check_toolchain import inspect_toolchain, toolchain_inputs


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--cc', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True)
    parser.add_argument('--wii-devkitpro', type=Path)
    parser.add_argument('--private-tag-data', type=Path)
    args = parser.parse_args()
    root = Path.cwd().resolve()
    output = args.output.resolve()
    if not output.is_relative_to(root) or output == root:
        parser.error('output must be an ignored subdirectory of this checkout')
    ignored = subprocess.run(['git', 'check-ignore', '--quiet', str(output) + os.sep])
    if ignored.returncode != 0:
        parser.error('output must be ignored by Git before any generated bytes are written')
    if output.exists():
        parser.error('new output directory required; existing evidence is preserved')
    compiler = args.cc.resolve(strict=True)
    environment = os.environ.copy()
    overrides = ('GCC_EXEC_PREFIX', 'COMPILER_PATH', 'LIBRARY_PATH', 'CPATH', 'C_INCLUDE_PATH',
                 'CPLUS_INCLUDE_PATH', 'OBJC_INCLUDE_PATH', 'DEPENDENCIES_OUTPUT', 'SUNPRO_DEPENDENCIES')
    for name in overrides:
        environment.pop(name, None)
    environment['PATH'] = str(compiler.parent) + os.pathsep + environment.get('PATH', '')
    target = subprocess.check_output([str(compiler), '-dumpmachine'], env=environment, text=True).strip()
    if (target == 'powerpc-eabi') != bool(args.wii_devkitpro):
        parser.error('PowerPC requires --wii-devkitpro; host compiler must omit it')
    sources = [Path('tools/wii')/name for name in ('cache_address_probe.c', 'cache_address_fixture.c',
                                                 'cache_address_owned.c', 'cache_address_main.c')]
    inputs = sources + [Path('tools/wii')/name for name in ('cache_address_probe.h', 'cache_address_fixture.h',
                                                          'cache_address_owned.h', 'run_cache_address.py',
                                                          'build.py', 'check_toolchain.py')]
    inputs += [Path('source/cache/cache_files.c'), Path('source/cache/physical_memory_map.c'),
               Path('source/cache/physical_memory_map.h'), Path('port/linux/include/halo_port_capacity.h')]
    hashes = {p.as_posix(): hashlib.sha256(p.read_bytes()).hexdigest() for p in inputs}
    source_commit = subprocess.check_output(['git', 'rev-parse', 'HEAD'], text=True).strip()
    dirty = bool(subprocess.check_output(['git', 'status', '--porcelain', '--', *map(str, inputs)], text=True))
    payload = b''
    count = table_crc = 0
    if args.private_tag_data:
        private_path = args.private_tag_data.resolve(strict=True)
        if private_path.is_relative_to(root):
            parser.error('private source data must stay outside the repository')
        if not 36 <= private_path.stat().st_size <= 0x1600000:
            parser.error('private tag blob must be 36 bytes to 22 MiB')
        payload = private_path.read_bytes()
        address, _, _, count = struct.unpack_from('<4I', payload)
        offset = address - 0x803A6000
        if not 1 <= count <= 65535 or offset < 36 or offset > len(payload) - count * 32:
            parser.error('private index table extent invalid')
        table_crc = zlib.crc32(payload[offset:offset + count * 32])
    sdk_identity = {}
    inventory = None
    if args.wii_devkitpro:
        sdk = args.wii_devkitpro.resolve(strict=True)
        inventory = inspect_toolchain(sdk)
        if inventory['errors']:
            raise ValueError('Wii preflight failed: ' + '; '.join(inventory['errors']))
        if compiler != Path(inventory['tools']['powerpc-eabi-gcc']['path']).resolve():
            parser.error('compiler does not belong to selected SDK')
        fingerprint = hashlib.sha256()
        for p in toolchain_inputs(sdk):
            fingerprint.update(p.relative_to(sdk).as_posix().encode() + b'\0')
            if p.is_file():
                fingerprint.update(hashlib.sha256(p.read_bytes()).digest())
        sdk_identity['toolchain_tree_sha256'] = fingerprint.hexdigest()
    record = {'scope':'isolated_xbox_index_address_diagnostic_not_engine_conversion',
              'source_commit':source_commit, 'source_dirty':dirty, 'inputs_sha256':hashes,
              'private_input_bytes':len(payload), 'private_input_sha256':hashlib.sha256(payload).hexdigest() if payload else None,
              'private_input_crc32':zlib.crc32(payload), 'private_tag_count':count, 'private_table_crc32':table_crc,
              'compiler':subprocess.check_output([str(compiler), '--version'], env=environment, text=True).splitlines()[0],
              'compiler_sha256':hashlib.sha256(compiler.read_bytes()).hexdigest(), 'target':target,
              'cleared_child_environment_overrides':list(overrides), 'sdk_identity':sdk_identity,
              'commands':[], 'state':'incomplete'}
    build_id = hashlib.sha256(json.dumps(record, sort_keys=True).encode()).hexdigest()[:16]
    record['build_id'] = build_id
    output.mkdir(parents=True)
    record_path = output/'cache-info.json'
    def save():
        record_path.write_text(json.dumps(record, indent=2)+'\n', encoding='utf-8')
    save()
    header = output/'cache_probe_payload.h'
    with header.open('w', encoding='ascii') as stream:
        stream.write(f'#define CACHE_PROBE_BUILD_ID "{build_id}"\n#define CACHE_PRIVATE_SIZE {len(payload)}\n')
        stream.write(f'#define CACHE_PRIVATE_CRC {zlib.crc32(payload)}u\n#define CACHE_PRIVATE_COUNT {count}u\n')
        stream.write(f'#define CACHE_PRIVATE_TABLE_CRC {table_crc}u\n')
        if payload:
            stream.write('static const unsigned char cache_private_bytes[] = {\n')
            for i in range(0, len(payload), 24):
                stream.write(','.join(str(b) for b in payload[i:i+24])+',\n')
            stream.write('};\n')
    flags = ['-std=c11', '-O2', '-Wall', '-Wextra', '-Werror', '-fstack-usage', '-I', 'tools/wii', '-I', str(output)]
    if inventory:
        flags += ['-DGEKKO', '-mrvl', '-mcpu=750', '-meabi', '-mhard-float', '-I', str(sdk/'libogc/include')]
    record['flags'] = flags
    def run(argv):
        p = subprocess.run(argv, env=environment, capture_output=True, text=True)
        record['commands'].append({'arguments':argv, 'exit_code':p.returncode, 'stdout':p.stdout.splitlines(),
                                   'stderr':p.stderr.splitlines()})
        save()
        if p.stdout: print(p.stdout, end='')
        if p.stderr: print(p.stderr, end='', file=__import__('sys').stderr)
        p.check_returncode()
        return p
    objects = []
    for source in sources:
        obj = output/(source.stem+'.o')
        run([str(compiler), *flags, '-c', str(source), '-o', str(obj)])
        objects.append(str(obj))
    if inventory:
        elf, dol = output/'cache_address.elf', output/'cache_address.dol'
        run([str(compiler), *objects, '-mrvl', '-mcpu=750', '-meabi', '-mhard-float',
             '-Wl,-Map,'+str(output/'cache_address.map'), '-L', str(sdk/'libogc/lib/wii'),
             '-lfat', '-logc', '-lm', '-o', str(elf)])
        record['elf'] = verify_elf(elf)
        run([inventory['tools']['elf2dol']['path'], str(elf), str(dol)])
        verify_dol(dol)
        record['state'] = 'compile_pass'
    else:
        exe = output/('cache_address.exe' if os.name == 'nt' else 'cache_address')
        run([str(compiler), *objects, '-o', str(exe)])
        executed = run([str(exe)])
        record['report'] = executed.stdout.splitlines()
        record['state'] = 'execution_pass'
    record['artifacts_sha256'] = {p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in output.iterdir()
                                 if p.name == 'cache_address' or p.suffix in ('.o', '.su', '.exe', '.elf', '.dol', '.map')}
    record['generated_payload_sha256'] = hashlib.sha256(header.read_bytes()).hexdigest()
    save()
    print(f'Cache address diagnostic build={build_id} state={record["state"]}')


if __name__ == '__main__':
    main()
